name: Build and Publish Container and Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: github-repository
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Set up Go ^1.18
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Unit Test
        run: make test

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Code specific changes
        id: code-specific-changes
        uses: tj-actions/changed-files@v23
        with:
          files_ignore: |
            charts
            .github
            .run

      - name: Automated Code Version Bump
        if: steps.code-specific-changes.outputs.any_modified == 'true'
        id: code-version-bump
        uses: phips28/gh-action-bump-version@v9.0.27
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        with:
          commit-message: 'CI: Bump app version to {{version}} [skip ci]'

      - name: Set up Docker Buildx
        if: steps.code-specific-changes.outputs.any_modified == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: steps.code-specific-changes.outputs.any_modified == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push merge to main
        if: steps.code-specific-changes.outputs.any_modified == 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.github-repository.outputs.lowercase }}:${{ steps.code-version-bump.outputs.newTag }},${{ steps.github-repository.outputs.lowercase }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"